apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipwright.fullname" . }}
  labels:
    {{- include "shipwright.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "shipwright.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "shipwright.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "shipwright.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args: ["/app/shipwright", "--debug"]
          env:
            - name: SHIPWRIGHT_NAMESPACES
              value: {{ join "," .Values.config.namespaces | quote }}
            - name: SHIPWRIGHT_INTERVAL
              value: {{ .Values.config.interval | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
